### PR TITLE
Add react i18next (multi-language support)

### PR DESCRIPTION
**Pull request by CRBroughton**
## Description

Installs react-i18next for multiple language support; I've added the required dependencies as well as adding a basic example into the App.tsx file. This PR does require the other PR's to first be reviewed and merged.

### CODE REVIEW

**Comment by CRBroughton** [comment]
Updated the PR with the changes from V1.0 branch - Should be good to merge in :partying_face:

**Comment by vallezw** [comment]
Looks good, would you mind adding German, since Ill do the German translations right away when writing stuff @CRBroughton

**Comment by CRBroughton** [comment]
All done :)

**Review by vallezw — APPROVED** [review]
Thanks!

**Pull request merged**
